apiVersion: v1
kind: Secret
metadata:
  name: portal-secret
  namespace: default
type: Opaque
stringData:
  SHARED_SECRET_KEY: "CHANGE ME"
  SQLALCHEMY_DATABASE_URI: "postgresql://CHANGE ME:CHANGE ME@postgres-service:5432/CHANGE ME"
  PROCESSING_SERVICE_URL: "http://processing-service:6000/process-application"
