"""adding the 'applications' table

Revision ID: 095f3a0c043b
Revises: 0af3db2ca88f
Create Date: 2026-07-19 21:48:13.957083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095f3a0c043b'
down_revision = '0af3db2ca88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('medical_certificate', sa.String(), nullable=False),
    sa.Column('gpa', sa.Integer(), nullable=False),
    sa.Column('flight_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
