"""adding status column to the 'applications' table

Revision ID: 993bf6b036e3
Revises: 095f3a0c043b
Create Date: 2026-07-19 22:30:55.039469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993bf6b036e3'
down_revision = '095f3a0c043b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
